app/views/shared/_search_panel.html.haml

This adds a title attribute to the search view icons.  The title attribute will show up as a tooltip in all major browsers, appearing when a cursor hovers over the icon.  This addresses the need to clarify the icons in task #7752 https://issues.dp.la/issues/7752

add tooltips for search view icons

---

app/assets/stylesheets/vendor/main.css
app/views/shared/results/_search_results.html.haml

This changes the styling of the message that appears on `/search`, `/map`, `/timeline`, and `/bookshelf` telling people how many results their query returned, and how their results are presented on data visualizations.  It removes the box around the latter part of the message so that it no longer looks like a button.  It also changes the HTML element from `h4` to `p`, which is more accurate markup.

remove border around search view explanations

---

app/views/map/show.html.haml

This adds a sentence of instructions for the map view.
This fixes task #7759 https://issues.dp.la/issues/7759

add map instructions

---

app/assets/javascripts/vendor/main.js
app/assets/stylesheets/vendor/main.css
app/views/map/show.html.haml
app/views/shared/_aside_toggle.html.haml
app/views/shared/_refine_control.html.haml
app/views/shared/_sidebar.html.haml
app/views/timeline/show.html.haml
config/settings.yml

This shows facets by default on `/map` and `/timeline` views.  
It also clarifies the language on the buttons that hide and show the facets.
This has been tested locally in desktop and mobile views.
This addresses task #7756 https://issues.dp.la/issues/7756

Show facets by default map and timeline.

---

app/assets/stylesheets/vendor/main.css
app/views/map/show.html.haml

This addresses tasks 7756 and 7759.  Two previous branches have addressed these tasks and were both merged to master and deployed to staging.  Once on stating, I tested the previous commits on mobile devices.  Based on this mobile testing, I was able to make the additional layout improvements in this branch.  
Links to tasks: https://issues.dp.la/issues/7756 https://issues.dp.la/issues/7759
This branch moves the map instructions so they are hidden when the map is hidden on mobile devices.  It also restyles the instructions and removes some inherited padding around the map.
This branch has been deployed to staging.

move and restyle map instructions

---

Gemfile

Add specific version limits to devise and better_errors gems, so that they do not upgrade to breaking version numbers, and so that new installations do not run into errors.  The latest version of better_errors wants Ruby 2 (while we are using 1.9), and devise v3+ requires changes to our configuration to avoid errors on startup, and is untested with our application.
A bundle update on an old installation will trigger the errors mentioned above.

Fix devise and better_errors versions in Gemfile

---

app/controllers/bookshelf_controller.rb
app/models/bookshelf.rb

Make one of the queries that's done for bookshelf items stop requesting facets.  The facets are not used and result, theoretically, in unnecessary work for the search servers.
I'm not sure how much this will cut down on the search servers' load, but the facets are unnecessary for the list of books.

Remove facets from bookshelf query

---

app/assets/javascripts/backbone/views/stacklife/base.js.coffee
app/controllers/application_controller.rb
app/controllers/bookshelf_controller.rb
app/models/permitted_params.rb
config/settings.local.yml.example
lib/errors/page_limit_error.rb

Have the BookshelfController respond with a 400 Bad Request if queried
with a page number that is above a configurable limit.
High page numbers can result in inefficient Elasticsearch queries.
See "Deep Paging in Distributed Systems," in
https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html
Also includes a fix to a Coffeescript file to fix an exception related to an object
being null sometimes.  (Which should remain its own commit.)

Limit the maximum page number that can be requested of the bookshelf

---

Gemfile

Pin rails_config to version 0.4.0 to prevent the error
"NameError: uninitialized constant Settings." after a new install or a
bundle update.
Same issue as
https://github.com/dpla/KriKri/commit/23a81cb33827b80df2d40d2cab87c96c0311cd14

Pin rails_config to version 0.4.0

---

app/controllers/bookshelf_controller.rb
app/models/permitted_params.rb

dpla/frontend#62 was designed to limit high-paging into bookshelf search requests.
This introduced a regression where all requests that used a `:page` parameter would
fail past the value set for `bookshelf.max_pages` in the settings.

Ensure page limits are only enforced on bookshelf (fixes #7915)

---

Gemfile

**PLEASE TEST ALL FRONTEND BEHAVIOR IMPLEMENTED IN BACKBONE/COFFEESCRIPT WHEN TESTING.** The [related issue](https://issues.dp.la/issues/7954) concerns the bookshelf, but please also test the map and the timeline to ensure that there are no regressions. 
Because of a change in our deployment processes introduced by dpla/automation#95, rails-backbone was being updated automatically. I'm not sure if it's an issue with this gem itself or one if its dependencies, but pinning it has the side effect of also pinning coffee-script, ejs, and jquery-rails.

Pin rails-backbone to ~> 0.9.10 (fixes #7954)

---

Gemfile
app/views/shared/_top_navigation.html.haml

* Add "GIF IT UP" under "Get Involved".
* Remove "Tutorials" from under "Help".
* Remove "Accounts" from under "Help".
* Remove "Shop" from under "Get Involved".

Changes to top-level menu items (fixes #8054)

---

app/assets/javascripts/backbone/models/timeline_item.js.coffee
app/assets/javascripts/backbone/templates/bookshelf/bookPreview.jst.ejs
app/assets/javascripts/backbone/templates/timeline/item.jst.ejs
app/assets/javascripts/map.js.coffee
app/models/search.rb
app/models/timeline.rb
app/views/search/show.html.haml

This adds each item's "created date" (ie. `sourceResource.date.displayDate`) to the search results for the list, map, timeline, and bookshelf views.  It addresses [ticket #7755](https://issues.dp.la/issues/7755).  
For those views relying on JavaScript (or CoffeeScript), the process involves:
1. Requesting `sourceResource.date` from the API.
2. Parsing `displayDate`, keeping in mind that:
a. `sourceResource.date` or `displayDate` may be undefined
b. `displayDate` may be a String or an Array
3. Showing the date in the view.

add date to search results

---

app/views/shared/_top_navigation.html.haml

Change the DPLAfest link in the top menu to `http://dp.la/info/get-involved/dplafest/april-2016/`.  This addresses [ticket #8183](https://issues.dp.la/issues/8183).

change dplafest link

---

.travis.yml
Gemfile
app/models/item.rb
spec/models/item_spec.rb
spec/spec_helper.rb

Let me know if you think this needs a test; there are no tests for the `Item` model at all yet. :disappointed_relieved:

Ensure edm:object values are HTTP(S) URIs when building thumbnails

---

app/views/shared/_top_navigation.html.haml

Change the "Curation Corps" link in the navbar to "Ebooks".  This addresses [ticket #8358](https://issues.dp.la/issues/8358).

Update ebooks link in nav bar

---

config/settings.yml
lib/dpla/items.rb

Add a parameter to configure whether HTTParty verifies the SSL certificate of the API, if it's using SSL. This allows use of the frontend in a development setting with a self-signed certificate for the API.

Make verification of api's SSL cert optional

---

app/views/pages/home.html.haml

This removes the DPLAfest 2016 slide from the homepage slideshow.  It addresses [ticket #8386](https://issues.dp.la/issues/8386).

remove dplafest slide from homepage slideshow

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb

Remove ApplicationController's behavior to unset the "no cache" cookie with every request for a user who is not logged-in. Instead, unset the cookie when a logged-in user logs out.

Avoid setting Set-Cookie header unnecessarily

---

app/views/pages/home.html.haml

The current link to the NCDHC item in the homepage slider does not resolve.  Possibly its DPLA ID changed during a recent ingestion?  In any case, this PR fixes the URL.

fix link to ncdhc item in homepage slider

---

app/views/shared/sidebar/_refine_by_type.html.haml

This corrects the label of the type facet.  Before, it was incorrectly labeled "Format".  In all other places in the frontend application this field is referred to as "Type".  GG agrees that "Type" is the preferred label.
This has been tested locally.  It addresses [ticket #8445](https://issues.dp.la/issues/8445).

change facet labels from format to type

---

app/helpers/items_helper.rb
app/views/items/show.html.haml

This hyperlinks certain metadata field values in the `item#show` view.  If a metadata field is facetable (ie. type, partner, location), the values of these fields will link to searches with those facets applied. 
For example, in the screenshot below, you can see that the partner and contributing institution fields are hyperlinked.  If you were to click on "HathiTrust", it would take you to `/search?partner=HathiTrust`.
There are two exceptions: date is not linked b/c it would be a pain to deal with date ranges.  Language is not currently included on the item page, so it is also not linked (this will be addressed in ticket #8460).
The method that renders the relevant HTML snippets is `item_field`, in the items helper.   I added a param option, `:facet`, that will create the necessary link. …

link facetable metadata value on item view

---

app/views/apps/index.html.haml

This adds pagination links to the bottom of the apps page.
This addresses [ticket #7785](https://issues.dp.la/issues/7785).  It has been tested on staging.

add pagination at bottom of page

---

app/helpers/result_manipulation_helper.rb
app/models/permitted_params.rb
spec/models/permitted_params_spec.rb

This sets the default search results per page to 20 on dp.la/search.  It changes both the API call and the default selected value in the dropdown menu.
This addresses [ticket #7754](https://issues.dp.la/issues/7754).  It has been tested locally.

change default search results per page to 20

---

app/views/search/show.html.haml

This fixes the display of the "type" field in the search results list view.  Before, if there were multiple types, they would display as an array:
Now, they display as a comma-separated string:
This has been tested locally.  It addresses [ticket #8458](https://issues.dp.la/issues/8458).

display multiple types

---

app/models/item.rb
app/views/items/show.html.haml
spec/models/item_spec.rb

This adds language metadata to the item view.
Language is parsed from the API response in the `Item` model.  `language` is a property of `sourceResource`.  Here is an example of the data structure as it comes in from the API:
The tests demonstrate the various safeguards against `nil` values and possible variances in the data structure.
This has been tested locally.  It addresses [ticket #8460](https://issues.dp.la/issues/8460).

add language metadata to item view

---

app/assets/stylesheets/vendor/main.css

This fixes there problem whereby on /item pages in certain mobile views, the "Contributing Institution" label was overlapping with the adjacent text.  
Before:
After:
This has been tested locally using the Chrome Device Mode developer tool.  It addresses [ticket #6533](https://issues.dp.la/issues/6533).

change label width

---

app/assets/stylesheets/vendor/main.css
app/views/items/show.html.haml

This aligns metadata fields on /item pages to make them easier to read/scan.  It left-aligns all metadata elements, instead of letting them wrap under the thumbnail image.  It also makes the the "Description" field conform stylistically with the other fields.  Before, "Description" had its own style, which disrupted the flow of the page.
Before:
After:
Out of scope for this PR is the issue where on small screens, labels such as "Contributing Institution" squish into the text to the immediate right.  That is addressed in another ticket.
This has been tested locally and on staging.  It addresses [ticket #7827](https://issues.dp.la/issues/7827).

realign metadata elements

---

app/views/shared/_sidebar.html.haml
app/views/shared/sidebar/_refine_by_date.html.haml
app/views/shared/sidebar/_refine_by_language.html.haml
app/views/shared/sidebar/_refine_by_location.html.haml
app/views/shared/sidebar/_refine_by_subject.html.haml
app/views/shared/sidebar/_refine_by_type.html.haml

This changes the order in which facets are displayed in the search, map, timeline, and bookshelf interfaces.  The new facet order was determined in consultation with MLB, MM, and DC after reviewing analytics data.
This also changes the subject facet so that it is, by default, expanded - previously, it was, by default, collapsed.  All other facets are expanded by default.
Finally, this removed the word "By" from facet titles for consistency - previously, some facets titles started with "By" and others did not.
This addresses [ticket #7753](https://issues.dp.la/issues/7753).  It has been tested locally.

reorder facets

---

app/controllers/map_controller.rb
app/controllers/timeline_controller.rb
app/views/shared/results/_search_results.html.haml

This fixes the count of total search results and the facets on map and timeline to match the results displayed in the map and timeline interfaces.
The map only displays items that have a value for `sourceResource.spatial.coordinates`.  The timeline only displays those that have a value for `sourceResource.date`.  However, before this PR, the API query that was used to generate the total search results and the facet filters returned all results, regardless of whether or not they had coordinates or dates.  This caused the results total and the facet filters to show more results than were actually present on the map or timeline.  Here is an example of this behavior on production: https://dp.la/map?utf8=%E2%9C%93&q=fish+taco  Note that the total and facets suggest there are three results, but …

show actual totals for map and timeline

---

app/views/timeline/show.html.haml

This fixes a bug in the timeline in which searches that include apostrophes were failing to generate a "Year" view.  
For instance: http://dp.la/timeline?q=%22valentine%27s+day%22&utf8=%E2%9C%93#/1905
Enclosing the search path in double quotes fixes the issue.  I also enclosed the item path, which is not currently an issue, but could be if we ever switch to using item URLs with keywords.
This has been tested locally. It addresses [ticket #7776](https://issues.dp.la/issues/7776).

enclose timeline paths in double quotes

---

app/views/map/show.html.haml

This fixes a bug in map where the map fails to render if the search term includes an apostrophe.
This has been tested locally.  It addresses [ticket #6388](https://issues.dp.la/issues/6388).

enclose map paths in double quotes

---

app/models/search.rb
app/views/shared/results/_search_results.html.haml
app/views/shared/sidebar/_refine_by_language.html.haml
app/views/shared/sidebar/_refine_by_location.html.haml
app/views/shared/sidebar/_refine_by_partner.html.haml
app/views/shared/sidebar/_refine_by_provider.html.haml
app/views/shared/sidebar/_refine_by_subject.html.haml

This PR addresses two related issues.
The first issue is including a message to the user of how many contributing institutions are represented in their search results.  Currently, the message a the top of the search results page says something like: "Your search returned 1,234 results."  The desired functionality is for the message to say something like:  "Your search returned 1,234 results from 56 contributing institutions."
The challenge here is that there is currently no way to get the total number of contributing institutions from the API.  The best we can do is total the contributing institutions facet, which is capped at 2,000.  No problem... unless a search result includes more than 2,000 contributing institutions!  The work-around MLB and I landed on is this: If there are less …

Increase num of facets in popups. Include provider in results count.

---

app/views/bookshelf/show.html.haml

This changes the message on the bookshelf view to include a link to info about DPLA ebooks, as per MLB's request.
This has been tested locally.  It addresses [ticket #8435](https://issues.dp.la/issues/8435).

change discontinue message on bookshelf view

---

app/assets/javascripts/backbone/templates/timeline/item.jst.ejs
app/assets/javascripts/map.js.coffee
app/helpers/application_helper.rb
app/views/items/show.html.haml
app/views/saved_lists/_list.html.haml
app/views/saved_lists/index.html.haml
app/views/search/show.html.haml
spec/helpers/application_helper_spec.rb

This fixes the new wording of the "View object" links ([PR#97](https://github.com/dpla/frontend/pull/97)).  The bug was discovered on staging, and was _not_ deployed to production.  
With these changes, the value of `sourceResource.type` will display in the link if it is a single-value Array (before, it was not displaying).  I also took the opportunity to abstract out the ruby-language code to a helper method and write a series of tests.
This has been tested locally and on staging.  It addresses [ticket #8436](https://issues.dp.la/issues/8436).

fix view object link to accept single array value for type

---

app/views/bookshelf/show.html.haml

Fix a typo in the ebooks URL on bookshelf.

fix typo in ebooks URL

---

app/controllers/apps_controller.rb

This increases the number of apps we show per page from 12 to 60 on dp.la/apps.  We currently have 32 apps, and don't add them very rapidly.  This will eliminate the need for pagination, at least for the near future, exposing users to our full app abundance on one delightful page.
This addresses [ticket #7760].  It has been tested on staging.

increase apps per page to 60

---

app/assets/stylesheets/vendor/main.css
app/views/search/show.html.haml

This fixes design inconsistencies in the headers on /search, /map, and /timeline.  With this PR:
- `h1` text appears on all views
- Refine button appears in the same place
- White space surrounding `h1` and refine buttons are consistent
Before:
After:
This has been tested locally using Chrome Device Mode.  It addresses [ticket #7825](https://issues.dp.la/issues/7825).

Consistent header display across mobile search interfaces

---

app/assets/javascripts/vendor/main.js
app/views/pages/home.html.haml

This changes the behavior of the homepage slideshow to be more user-friendly and intuitive.  Before, in order to link to the page represented by the slide image, the user had to click on an button labeled "i", and then click on the link that appeared overtop of the image.  Now, the user can click directly on the image at any time to follow the link.  There is not "i" button; the link appears when the user mouses over the slide image.
This has been tested locally and on staging.  It addresses [#8133](https://issues.dp.la/issues/8133).

direct link from slideshow images

---

app/assets/stylesheets/vendor/main.css
app/views/shared/_search_panel.html.haml

This adds labels under the icons for List, Map, and Timeline in order to make them easier for users to understand.  Tweaks to the CSS make the layout look nice with the labels.
Before:
After:
This has been tested locally, on staging, and with the Chrome device tool for mobile.  It addresses [ticket #7725](https://issues.dp.la/issues/7752).

add icon labels

---

Gemfile
app/helpers/items_helper.rb
app/models/item.rb
app/views/items/show.html.haml
spec/models/item_spec.rb

This activates links within metadata values in `/item` pages.
Metadata values such as rights statements may be URIs, or may include URIs within free text fields.  For example:
https://dp.la/item/b1947a688b43a6ce8aae6b5f25afd3d0
https://dp.la/item/8d0bd6f2d31be8b8ca88e519ccbab27e
This activates those links using the [Rinku](https://github.com/vmg/rinku) gem.  For the rights field specifically, it downcases the first letter if it is a URI.
Note: This _only_ links metadata fields that are _not_ facetable; facetable metadata values are already linked on `/item` pages.
This addresses [ticket #8705](https://issues.dp.la/issues/8507).  It has been tested locally.

auto-link item metadata

---

app/assets/stylesheets/vendor/main.css
app/views/items/show.html.haml

This fixes a couple of errors introduced when several different branches were merged to develop.  It eliminates typo in the items show view that was introduced while resolving a merge conflict.  It also adjusts the CSS so that the font size of the URL metadata field on the item show view is the same as the other metadata fields.

fix URL metadata field on item page

---

app/assets/javascripts/backbone/templates/timeline/item.jst.ejs

This removes a comment in `item.jst.ejs`.  The `#` in the comment line was causes asset compilation to fail in the production environment.  This has been tested on staging.

remove comment from jst.ejs file

---

Gemfile

This pins the breadcrumbs_on_rails gem to v2.3.  Version 3.0, released on Aug 7, requires ruby v2.0, which is not yet running in the frontend.

pin breadcrumbs_on_rails gem to v 2.3

---

app/models/item.rb
spec/models/item_spec.rb

This allows the frontend to handle multiple thumbnails (ie. `edm:object`s).  
Some providers are giving us multiple thumbnails.  Before this fix, the frontend would only render thumbnails if there was a single value.  If there were multiple values, it would default to showing the placeholder image (ie: https://dp.la/item/a88574851da78a86a59a2e94c5e3a7e3).
With this fix, if there are multiple thumbnails, the frontend will render the first.
This has been tested locally.  It addresses [ticket #8525](https://issues.dp.la/issues/8525).

handle multiple thumbnails

---

app/assets/javascripts/google-analytics-events.js
app/views/layouts/application.html.haml

This gracefully handles a missing Google Analytics tracker ID.  Before this PR, if the Google Analytics tracker was missing from the application settings, the google analytics rails gem would still send a signal to GA, with a dummy tracker ID.  This PR adds a conditional that checks for the presence of the tracker.
This addresses [ticket #8529](https://issues.dp.la/issues/8529).  It has been tested locally.

handle missing google analytics tracker

---

Gemfile

This pins all gems to the versions current running in production.

pin all gems to current production versions

---

app/models/item.rb

This handles multiple values for `object` in an ssl environment. 
This addresses [ticket #8525](https://issues.dp.la/issues/8525).  It has been tested on staging.

handle multiple objects in ssl item preview

---

lib/dpla/conditions.rb
spec/lib/dpla/conditions_spec.rb

Fixes https://issues.dp.la/issues/8398
Facilitate correct filtering based on clickthroughs from facets by doing an exact match on the facet values -- not a tokenized search.
See https://github.com/dpla/platform/pull/41
Also add some comments to the existing code.

Add exact field match to fix filtering on facets

---

app/views/shared/_top_navigation.html.haml

Change the DPLAfest link in the main menu.  This addresses [ticket #8552](https://issues.dp.la/issues/8552).

change dplafest menu link

---

Gemfile

This pins the rinku gem to version 2.0.0, which is necessary until we upgrade ruby to version 2.0.

pin rinku gem to version 2.0.0

---

Gemfile

The `rake` gem has had a new release that obsoletes some syntax that's used in our application. The error below is encountered when running `rake assets:precompile`.
See
http://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11
The solution is for us to run version 11.3.x of `rake`, which we've known to be good in production.  `Gemfile` is thus being modified in this commit to pin it.
The error message:
```
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000001cce808>
/home/dpla/frontend-git/Rakefile:8:in `<top (required)>'
```

Pin rake gem

---

.travis.yml

This forces travis to update its bundler gem before running gem dependency checks.  Before, it was running an older version of bundler, and was incorrectly detecting gem dependency conflicts that were not actually conflicts.

travis update bundler

---

Gemfile

This fixes a gem dependency problem that is currently blocking deployment.  It has been tested locally and on staging.

pin nokogiri gem version

---

app/views/pages/home.html.haml

This replaces the "Battle on the Ballot" slide with the DPLAfest 2017 slide.
This should not be deployed until [frontend-assets PR#9](https://github.com/dpla/frontend-assets/pull/9) has been merged.
This addresses [ticket DT-1113](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1113).

add homepage slide for dplafest 2017

---

app/views/items/show.html.haml

This changes the frontend item view so that "Rights" is displayed _after_ "Standardized Rights Statement".  
This branch has been deployed to staging for review.  You can see and example here: https://staging.dp.la/item/6300dab1395799d6bc0ba3b5e7d45d5a 
This addresses [ticket DT-1133](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1133).

change position of standardized rights statement on item page

---

app/models/item.rb

This is a temporary fix for NYPL rights statements.  It show the general rights field only if there is no standardized rights statement.  This is available for testing on staging:
NYPL record with both standardized and general rights statement (only standardized is displayed): https://staging.dp.la/item/2146cf147821298331afe95f2d2c92ef
NYPL record with only general rights statement: https://staging.dp.la/item/1998b3947afbb0089223ba351e39e2cb
Non-NYPL record with general rights statement: https://staging.dp.la/item/ce8bd5b62e05b0dd910dd5084e001b63
This addresses ticket [DT-1175](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1175)

temporary fix for nypl rights statement

---

app/controllers/subjects_controller.rb
app/helpers/refine_helper.rb
app/models/search.rb
app/views/shared/results/_search_results.html.haml
app/views/shared/sidebar/_refine_by_location.html.haml

Improve response times of the Timeline and other places where very large facets have been queried, processed, and rendered in the past.
* Reduce facet sizes
* Create querystrings more efficiently in self-referential hyperlinks in certain places that have large-domain `each` loops, where `#link_to` is too slow.
Note that the huge facets of 2000 elements were never used fully, because the most that was drawn into a given modal window on an HTML page was 10 "pages" of 30 elements. Only 300 facets were really being used out of the 2000 that Elasticsearch was being asked to assemble. The number of pages has been reduced to 8, and the facet size in a number of queries has been reduced to 240, which is 8 times 30.
See https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1190
When this …

Improve response times of various facets

---

app/views/layouts/application.html.haml

This adds the following `meta` tag to all pages:
```<meta name="referrer" content="origin-when-cross-origin" />```
The purpose of this tag is to enable `HTTP` sites (including a fair number of our contributors) to track traffic from DPLA using tools such as Google Analytics.
This also reformats what was a single line of code for legibility.
This has been deployed to staging for testing.  For example: view-source:https://staging.dp.la/item/2146cf147821298331afe95f2d2c92ef
This addresses [ticket DT-1116](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1116).

add meta referrer tag

---

app/views/shared/_top_navigation.html.haml

This removes the "Events" link from the "Get Involved" menu.  It has been tested on staging.  It addresses [DT-1195](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1195).

remove events from menu

---

app/models/item.rb
app/views/items/show.html.haml
config/rights_statements.yml
spec/models/item_spec.rb

This displays creative commons licenses.  
Creative commons URLs are added to the YML file which already has the info necessary to display rightsstatement.org statements.  It may seem a bit graceless to put the creative commons URLs here, but I think it will serve us well once we inevitably have to add display info, such as textual descriptions and image paths, as we did with rightsstatement.org.
Logic is added to the model to check the validity of standardized rights URIs coming through the API.  This fulfills the requirement of only displaying valid rights statements.
This has been deployed to staging.
- Item with creative commons statement: https://staging.dp.la/item/03b1a4cb920bdbbbf9f3251106350bfc
- Item with rightsstatement.org statement: …

display creative commons statements

---

app/helpers/items_helper.rb
app/models/item.rb
app/views/items/show.html.haml
config/rights_statements.yml
spec/helpers/items_helper_spec.rb
spec/models/item_spec.rb

This allows more variation in creative commons licenses that are displayed on item pages.
Before, cc licenses would only display if they exactly matched a set of URIs specified in `config/rights_statements.yml`.  This instead displays any statement that contains the substring `creativecommons.org`, allowing, for example, statements of different versions or statements without trailing backlashes.
Before, the logic to determine whether or not a standardized rights statement was valid for display purposes was in the `Item` model.  This PR moves the logic to a view helper since it's now more complex and more appropriate for a helper anyway.
This branch has been deployed to staging for review purposes:
* Item with creative commons statement: …

Fix creative commons license

---

config/environments/development.rb

config.assets.debug causes many 404s for assets when `RAILS_ENV=development`. If `foo.css` is included in `application.scss`, it's concatenated into the resulting `application.css` file, but Rails still writes a link tag in the HTML for foo.css. Since it's been included, it doesn't exist on its own in the public/assets directory and you get a 404. I'm not sure exactly how to get Rails to serve individual files instead of concatenating, but at least the concatenated `application.css` is readable, so it suffices for now.
`application.css` isn't the only one; I was getting 404s before for Javascript like the jQuery plugins, as well, before changing `config.assets.debug`.

Turn off asset debugging in development

---

app/views/pages/home.html.haml

This changes the first slide in the homepage slideshow from "DPLAfest" to "American Empire."  It also changes the URL of two additional slides to point to new, compressed versions of the images.
This addresses tickets [DT-362](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-632) and [DT-1339](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1339).

Dt 1339 change homepage slide
